apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: within-ws-rule
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project-name: team2
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          project-name: team2